FROM ubuntu:16.04

MAINTAINER Solomon Xie <solomonxiewise@gmail.com>

RUN apt-get update && \
    apt-get install curl wget git bashdb -y

RUN useradd -m -p "123" -s /bin/bash ubuntu && \
    usermod -aG sudo ubuntu && \
    su - ubuntu

WORKDIR /home/ubuntu

CMD /bin/bash
