FROM ubuntu:16.04

MAINTAINER Solomon Xie <solomonxiewise@gmail.com>

RUN apt-get update && \
    apt-get install sudo vim curl wget git vim bashdb -y

RUN useradd -m -s /bin/bash ubuntu && \
    usermod -aG sudo ubuntu && \
    echo "root:root123" | chpasswd && \
    echo "ubuntu:ubuntu123" | chpasswd && \
    su - ubuntu

WORKDIR /home/ubuntu

CMD /bin/bash
