FROM ubuntu:18.04
MAINTAINER Solomon Xie <solomonxiewise@gmail.com>

RUN apt-get update && apt-get upgrade
RUN apt-get install -y build-essential
RUN apt-get install -y libc6-dbg
RUN apt-get install -y gdb
RUN apt-get install -y valgrind
