# WsgiDAV configuration file
#
# MAINTAINER: Solomon Xie <solomonxiewise@gmail.com>
# ENVIRONMENT: Linux / Mac
# 
# 1. Rename this file to `wsgidav.yaml`
# 2. Adjust settings as appropriate
# 3. Run `wsgidav` from the same directory or pass file name with `--config` option.


# ============================================================================
# SERVER OPTIONS

server: "cheroot"
server_args: {}

host: 0.0.0.0
port: 80

verbose: 3
property_manager: true
mutable_live_props:
    - "{DAV:}getlastmodified"
emulate_win32_lastmod: true
lock_manager: true
unquote_path_info: false #: See issue #8
re_encode_path_info: null #: (See issue #73)

dir_browser:
    ignore:
        - ".DS_Store"  # macOS folder meta data
        - "Thumbs.db"  # Windows image previews
        - "._*"  # macOS hidden data files
    icon: true
    #response_trailer: true   # BUG, DOESN'T WORK
    show_user: true
    davmount: false
    ms_mount: false
    ms_sharepoint_support: true


# ==========================================================
# SHARES

#: Application root, applied before provider mapping shares,
#: e.g. <mount_path>/<share_name>/<res_path>
#: Supports relative path
mount_path: null  # root_path, NULL by default
provider_mapping:
    "/webdav": "/var/wsgidav/webdav"
    "/share": "/var/wsgidav/share"


# ===========================================================
# AUTHENTICATION
http_authenticator:
    domain_controller: null
    accept_basic: false
    accept_digest: true
    default_to_digest: true
    trusted_auth_header: null
    preset_domain: null
    preset_server: null

# These routes must match the provider mapping.
#
# NOTE: Provider routes without a matching entry here, are open for
# anonymous access!
user_mapping:
    "/webdav":
        "user1":
            password: "123"
            description: "Prime user for webdav"
            roles: []
        "user2":
            password: "456"
            description: "User 2 for webdav"
            roles: []
    "/share":
        "user1":
            password: "456"
            description: "User 1 for Share 2"
            roles: []
        "user2":
            password: "qwerty"
            description: "User 2 for Share 2"
            roles: []


