# MAINTAINER: Solomon Xie <solomonxiewise@gmail.com>
# ENVIRONMENT: Python on any Unix-like OS
#
# WsgiDAV configuration file
# How to run:
#   $ wsgidav --config=myconfig.yaml
#


# ============================================================================
# SERVER OPTIONS

host: 0.0.0.0
port: 80

# ==========================================================
# SHARES
#
#: Application root, applied before provider mapping shares,
#: e.g. <mount_path>/<share_name>/<res_path>
#: supports relative path
#mount_path: "/var/wsgidav/webdav"  # root_path, NULL by default
mount_path: null
provider_mapping:
    "/webdav": "/var/wsgidav/webdav"
    "/share": "/var/wsgidav/share"


# ===========================================================
# AUTHENTICATION
#
# These routes must match the provider mapping.
# Fail on matching, will be open for anonymous access!
user_mapping:
    "/webdav":
        "pi":
            password: "123"
            description: "Prime user for webdav"
            roles: []
        "user2":
            password: "456"
            description: "User 2 for webdav"
            roles: []
    "/share":
        "user1":
            password: "456"
            description: "User 1 for Share 2"
            roles: []
        "user2":
            password: "qwerty"
            description: "User 2 for Share 2"
            roles: []



# ===========================================================
# ADDITIONAL OPTIONS
#

server: "cheroot"
server_args: {}
verbose: 3

# Property Manager
# null: (default) Don't support dead properties
# true: Use in-memory property manager (NOT persistent)
property_manager: true

#:
lock_manager: true

#:Enable to allow clients to use e.g. the touch or cp / rsync commands with the
mutable_live_props:
    - "{DAV:}getlastmodified"

#:Handle Microsoft's Win32LastModifiedTime property.
emulate_win32_lastmod: true

#: Has to add, or can't connect with Mac/Cyberduck/Windows
add_header_MS_Author_Via: true  

#: Issues fixer
unquote_path_info: false #: See issue #8
re_encode_path_info: null #: (See issue #73)

#:WsgiDavDirBrowser
dir_browser:
    ignore:
        - ".DS_Store"
        - "Thumbs.db"
        - "._*"
    icon: true #:Display WsgiDAV icon in header
    show_user: true
    davmount: false
    ms_mount: false
    ms_sharepoint_support: true
    #response_trailer: true  # BUG, DOESN'T WORK

http_authenticator:
    domain_controller: null
    accept_basic: false
    accept_digest: true
    default_to_digest: true
    trusted_auth_header: null
    preset_domain: null
    preset_server: null

#: BUG, none works
#middleware_stack:
#    - wsgidav.debug_filter.WsgiDavDebugFilter
#    - wsgidav.error_printer.ErrorPrinter
#    - wsgidav.http_authenticator.HTTPAuthenticator
#    - wsgidav.dir_browser.WsgiDavDirBrowser
#    - wsgidav.request_resolver.RequestResolver
